model_name: coco_yolov4
data:
  train_annotation_path: /home/huffman/data/annotations/instances_train2017.json
  #  train_annotation_path: /home/huffman/data/annotations/instances_val2017.json
  val_annotation_path: /home/huffman/data/annotations/instances_val2017.json
  train_img_root: /home/huffman/data/train2017
  #  train_img_root: /home/huffman/data/val2017
  val_img_root: /home/huffman/data/val2017
  img_size: 672
  batch_size: 32
  num_workers: 8
  debug: False
  remove_blank: False
  use_crowd: False

model:
  num_cls: 80
  anchors: [[12, 16, 19, 36, 40, 28],
            [36, 75, 76, 55, 72, 146],
            [142, 110, 192, 243, 459, 401]]
  strides: [8, 16, 32]
  scale_name: s
  freeze_bn: False

hyper_params:
  iou_type: ciou
  multi_scale: [672]

optim:
  optimizer: SGD
  lr: 0.01
  momentum: 0.937
  alpha: 0.2
  gamma: 1.0
  warm_up_epoch: 3
  weight_decay: 0.0005
  epochs: 300
  sync_bn: True
val:
  interval: 1
  weight_path: weights
  conf_thresh: 0.001
  iou_thresh: 0.6
  max_det: 300
gpus: 6,7